src/main/java/org/bahmni/reports/model/Report.java
src/main/java/org/bahmni/reports/web/MainReportController.java
src/main/java/org/bahmni/reports/web/security/OpenMRSAuthenticator.java
src/main/java/org/bahmni/reports/web/security/ReportAuthorization.java
src/test/java/org/bahmni/reports/web/security/ReportAuthorizationTest.java

[BAH-395](https://bahmni.atlassian.net/browse/BAH-395)

BAH-395 | Sowmika, Raju | [Role Based Access To Reports] | Add authorization for individual report access

---

.gitignore
src/main/resources/liquibase.xml

https://bahmni.atlassian.net/browse/BAH-996

BAH-996 | Remove unused Liquibase ChangeSet

---

pom.xml

As part of [BAH-934](https://bahmni.atlassian.net/browse/BAH-934), I notice that Bahmni Reports returns `java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z`.
Update to a more recent Jackson does fix the error.
Complete stack.
```
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:397)
com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) …
```

BAH-934 | Upgrade Jackson Core dependency

---

src/main/java/org/bahmni/reports/model/BahmniForm.java

Fix for https://bahmni.atlassian.net/browse/BAH-1218

BAH-1218 | Fix for form builder reports failing

---

.github/download_artifact.sh
.github/workflows/build_publish.yml
.github/workflows/validate_pr.yml
.mvn/wrapper/maven-wrapper.properties
README.md
mvnw
mvnw.cmd
package/docker/bahmni-reports/Dockerfile
package/docker/bahmni-reports/start.sh
package/docker/bahmni-reports/template/bahmni-reports.properties.template
package/resources/log4j2.properties
package/resources/run-liquibase.sh
pom.xml

- dockerised bahmni-reports
- github actions for build and publish to docker hub
- github actions for PR validation

BAH-1421 | Dockerise Bahmni-reports

---

.github/workflows/build_publish.yml
.github/workflows/validate_pr.yml
README.md
package/docker/bahmni-reports/template/bahmni-reports.properties.template
scripts/create_configuration.sh
src/main/java/org/bahmni/reports/web/security/OpenMRSAuthenticator.java
src/main/java/org/bahmni/reports/web/security/Privilege.java
src/main/java/org/bahmni/reports/web/security/Privileges.java
src/main/java/org/bahmni/reports/web/security/ReportAuthorization.java
src/main/resources/log4j2.properties
src/test/java/org/bahmni/reports/BahmniReportsConfigurationTest.java
src/test/java/org/bahmni/reports/report/integrationtests/BaseIntegrationTest.java
src/test/java/org/bahmni/reports/scheduler/CleanReportsJobTest.java
src/test/java/org/bahmni/reports/scheduler/ReportsSchedulerTest.java
src/test/java/org/bahmni/reports/web/security/ReportAuthorizationTest.java

- Made **Privilege** and **Privileges** into public class and code refactoring is done.
- Fix '**?**' and '**≤**' issue for some test cases by adding **utf encoding** for the **reports_integration_tests schema.**
- Added PowerMockIgnore annotations for few classes
- Changes done for log4j error fix in log4j2.properties file
- Ignored a test case in BahmniReportsConfigurationTest.java
- Github workflow for test and packaging

Fix errors and failing test cases. Dockerise bahmni-reports

---

src/main/java/org/bahmni/reports/filter/JasperResponseConverter.java

This PR is about
- Removal of file deletion code
https://bahmni.atlassian.net/browse/BAH-1872

BAH-1872 - | Rohit | - Comments file deletion code

---

package/docker/bahmni-reports/template/bahmni-reports.properties.template
scripts/create_configuration.sh
src/main/java/org/bahmni/reports/BahmniReportsProperties.java
src/main/java/org/bahmni/reports/util/BahmniReportUtil.java
src/main/java/org/bahmni/reports/web/ReportHeader.java

BAH-2131 | Report-generated-on time-is-incorrect-in-report

BAH-2131|Report-generated-on time-is-incorrect-in-report

---

.github/workflows/build_publish.yml
package/docker/bahmni-reports/Dockerfile

- Uses versioning utility from bahmni-infra-utils
- Uses `bahmni-embedded-tomcat` artifact from S3 repository

BAH-2287 | Implement release versioning

---

.github/workflows/build_publish.yml
.github/workflows/validate_pr.yml

Co-authored-by: Siva Reddy <sivareddy.pathuri@thoughtworks.com>
JIRA https://bahmni.atlassian.net/browse/BS-39
Published Images Screenshot

BS-39 | Siva,Vijay | Publish bahmni-reports with SNOMED image tags

---

package/docker/bahmni-reports/start.sh
src/main/resources/liquibase.xml

JIRA card -> [https://bahmni.atlassian.net/browse/BAH-2736](https://bahmni.atlassian.net/browse/BAH-2736)

Bindu | BAH-2736 | add precondition for reports-user creation

---

src/main/java/org/bahmni/reports/template/TSIntegrationDiagnosisReportTemplate.java
src/main/resources/sql/tsIntegrationDiagnosisCount.sql
src/test/java/org/bahmni/reports/report/TSIntegrationDiagnosisReportTest.java

1)Add summary total
2)Replace short name instead of FSN 
3)Rename Total to Count
https://bahmni.atlassian.net/browse/BS-141

BS - 141 | Vijay | Add summary total and replace with short name instead of FSN

---

package/docker/bahmni-reports/template/bahmni-reports.properties.template
scripts/create_configuration.sh
src/main/java/org/bahmni/reports/BahmniReportsProperties.java
src/main/java/org/bahmni/reports/util/BahmniReportUtil.java
src/main/java/org/bahmni/reports/web/ReportHeader.java

Jira -> https://bahmni.atlassian.net/browse/BAH-2131
Jira -> https://bahmni.atlassian.net/browse/BAH-3005
The timezone issue that was reported in [BAH-2131](https://bahmni.atlassian.net/browse/BAH-2131) was resolved when configuring the timezone as part of card [BAH-3005](https://bahmni.atlassian.net/browse/BAH-3005). The changes in [Bahmni/bahmni-docker](https://github.com/Bahmni/bahmni-docker/pull/45) would take care of the incorrect time in the reports header. The timezone conversions made as part of [BAH-2131](https://bahmni.atlassian.net/browse/BAH-2131) are hence being reverted.

Revert "BAH-2131 | Report-generated-on time-is-incorrect-in-report"

---

.github/workflows/build_publish.yml
src/main/java/org/bahmni/reports/model/TSIntegrationDiagnosisReportConfig.java
src/main/java/org/bahmni/reports/template/TSIntegrationDiagnosisReportTemplate.java
src/main/resources/sql/tsIntegrationDiagnosisCount.sql
src/test/java/org/bahmni/reports/report/TSIntegrationDiagnosisReportTest.java

Fix for diagnosis count not showing results in clinic config using tsConceptSource and conceptNameDisplayFormat attributes
https://bahmni.atlassian.net/browse/BS-166

BS - 166 | Vijay | fix for diagnosis count not showing results in clinic config

---

src/main/java/org/bahmni/reports/dao/impl/GenericObservationFormDaoImpl.java
src/main/java/org/bahmni/reports/dao/impl/ObservationFormDaoImpl.java
src/main/java/org/bahmni/reports/model/GenericObservationReportConfig.java
src/main/java/org/bahmni/reports/util/GenericObservationFormReportTemplateHelper.java
src/main/java/org/bahmni/reports/util/GenericObservationReportTemplateHelper.java
src/main/resources/sql/observationFormReport.sql

Jira Card: [BAH-3066](https://bahmni.atlassian.net/browse/BAH-3066)
This PR addresses the issue related to the report of "type": "formBuilder" in Bahmni. Currently, the report displays concepts in all languages instead of the preferred Locale, and the Fully Specified Name (FSN) is returned instead, even when the Short Name Preferred format is specified.
To resolve these issues, the following changes have been made:
- **Introduction of a new key "preferredLocale"**
This key allows specifying a preferred Locale for the report. When set, the report will display the results in the given Locale, resolving the problem of concepts being displayed in multiple languages.
- **Update of the constructConceptNameSelectSql Method**
The query responsible for displaying concepts in the report has been …

[Rahul] | BAH-3066 | Add. Filter For Preferred Locale

---

.github/workflows/build_publish.yml
.github/workflows/validate_pr.yml
pom.xml

JIRA -> [BAH-3197](https://bahmni.atlassian.net/browse/BAH-3197)
In this PR, the following modifications have been implemented:
Dependency Update: A few dependencies have been updated to their immediate stable versions.
This would fix most of our vulnerabilities except the following :
There is no direct fix for the above vulnerabilities and further investigation needs to be done for the above vulnerabilities.

[Parvathy, Rahul] | BAH-3197 | Add. Latest Stable Packages For Security

---

package/resources/run-liquibase.sh

JIRA -> [BAH-3197](https://bahmni.atlassian.net/browse/BAH-3197)
In this PR, the MYSQL_CONNECTER_JAR path has been updated to fix the MySQL Connection Error.

[Parvathy, Rahul] | BAH-3197 | Fix. MySQL Connection Error

---

.travis.yml
pom.xml

JIRA -> [BAH-3197](https://bahmni.atlassian.net/browse/BAH-3197)

BAH-3197 | Fix. Bump Jdk Version 8 -> 11

---

pom.xml

This PR  upgrades the JDBC driver version to latest to support Postgres 16 for Odoo 16 reports.

BAH-4068 | Fix. Upgrade postgres JDBC driver version

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd
package/docker/bahmni-reports/Dockerfile
pom.xml
src/main/java/org/bahmni/reports/util/SqlUtil.java
src/test/java/org/bahmni/reports/util/SqlUtilTest.java

JIRA -> [BAH-3884](https://bahmni.atlassian.net/browse/BAH-3882)
In this PR, the following changes have been added to resolve the major vulnerabilities:
- Dependency Upgrades
- Maven Wrapper Upgrade
The following vulnerability will be resolved as part of the spring migration.

BAH-3884 | Fix. Bump Dependencies With Vulnerabilities

---

pom.xml

JIRA -> [BAH-4097](https://bahmni.atlassian.net/browse/BAH-4097)
For Standard Release.

BAH-4097 | Add. Bump Version 0.94 -> 1.1
